version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: 4dx-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: 4dx
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - 4dx-network

volumes:
  mysql_data:

networks:
  4dx-network: